/occupancy_map/occupancy_map_node:
  ros__parameters:
    sensor_input_mode: 0 # 0 camera 1: lidar
    localization_mode: 0 # 0: pose (default) 1: odom
    # depth_image and pointcloud topics
    depth_image_topic: /world/maze/model/x500_depth_1/link/OakDLite/base_link/sensor/StereoOV7251/depth_image
    point_cloud_topic: /world/maze/model/x500_depth_1/link/OakDLite/base_link/sensor/StereoOV7251/depth_image/points
    pose_topic: /px4_visualizer/px4_1/vehicle_pose
    odom_topic: /px4_1/fmu/out/vehicle_odometry
    # robot size
    robot_size: [0.5, 0.5, 0.3]

    # Camera Parameters
    depth_intrinsics: [432.496042035043, 432.496042035043, 320.0, 240.0] # fx, fy, cx, cy from camera_info
    depth_scale_factor: 10.0 # 1000 for Intel Realsense Camera
    depth_min_value: 0.5
    depth_max_value: 5.0
    depth_filter_margin: 2 # filter
    depth_skip_pixel: 2 # filter
    image_cols: 640
    image_rows: 480
    body_to_camera: [
      1.0, 0.0, 0.0, 0.12,
      0.0, 1.0, 0.0, 0.03,
      0.0, 0.0, 1.0, 0.242,
      0.0, 0.0, 0.0, 1.0
    ]  # pose from base_link to camera from SDF

    # Raycasting
    raycast_max_length: 5.0
    p_hit: 0.70
    p_miss: 0.35
    p_min: 0.12
    p_max: 0.97
    p_occ: 0.80

    # Map
    map_resolution: 0.1
    ground_height: -0.1 # m
    map_size: [40.0, 40.0, 3.0] # meter. in x y z direction (reserved size)
    local_update_range: [5.0, 5.0, 5.0]
    local_bound_inflation: 3.0 # inflate local bound in meter
    clean_local_map: false

    # visualziation
    local_map_size: [40.0, 40.0, 6.0] # meter. in x y z direction (only for visualization)
    max_height_visualization: 2.5 # m
    visualize_global_map: true
    verbose: false

    prebuilt_map_directory: "No"
    # prebuilt_map_directory: "path/to/static_map.pcd"